version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install Packages...
      - yarn install
  build:
    commands:
      - echo Build WebApp
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'