describe('Chat', () => {


  it('Arbitrator settings', () => {
    cy.login(Cypress.env('userSeller'))
    cy.wait(10000)

    cy.get('[data-cy=headerProfileToggler]').click()
    cy.wait(1000)
    cy.get('[data-cy=profile]').contains('Profile').click()
    cy.wait(2000)

    // enable and set arbitrator settings
    cy.get('[data-cy=arbitratorSettingsEnabled]')
      .parent()
      .click('left')
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .clear()
      .type(10)
      .should('have.value', 10)
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .clear()
      .type(5)
      .should('have.value', 5)
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .clear()
      .type('cypress{enter}')
      .get('[class=css-1rhbuit-multiValue]')
      .contains('cypress')
    cy.get('[data-cy=arbitratorSettingsSubmit]')
      .click()

    cy.wait(1000)

    // check arbitrator settings
    cy.visit(Cypress.env('host'))
    cy.get('[data-cy=headerProfileToggler]').click()
    cy.wait(1000)
    cy.get('[data-cy=profile]').contains('Profile').click()
    cy.wait(2000)
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .should('have.value', 10)
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .should('have.value', 5)
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .get('[class=css-1rhbuit-multiValue]')
      .contains('cypress')

    // disable arbitrator
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsEnabled]')
      .parent()
      .click('left')
    cy.get('[data-cy=arbitratorSettingsSubmit]')
      .click()
  })
})