describe('Chat', () => {


  it('Arbitrator settings', () => {
    cy.login(Cypress.env('userSeller'))
    cy.wait(10000)

    cy.get('[data-cy=headerProfileToggler]').click()
    cy.wait(1000)
    cy.get('[data-cy=profile]').contains('Profile').click()
    cy.wait(2000)

    cy.get('[data-cy=profileBio]')
      .clear()
      .type("Ceci n'est pas une biographie.")
      .should('have.value', "Ceci n'est pas une biographie.")

    cy.get('[data-cy=profileAddress]')
      .clear()
      .type("Viale Regina Margherita, 71")
      .should('have.value', "Viale Regina Margherita, 71")
    cy.get('[data-cy=profileAddressCity]')
      .clear()
      .type("Cagliari")
      .should('have.value', "Cagliari")
    cy.get('[data-cy=profileAddressZip]')
      .clear()
      .type("09124")
      .should('have.value', "09124")
    cy.get('[data-cy=profileAddressState]')
      .clear()
      .type("CA")
      .should('have.value', "CA")
    cy.get('[data-cy=profileAddressCountry]')
      .clear()
      .type("Italy")
      .should('have.value', "Italy")

    // enable and set arbitrator settings
    cy.get('[data-cy=arbitratorSettingsCollapse]')
      .click()
    cy.get('[data-cy=arbitratorSettingsEnabled]')
      .parent()
      .click('left')
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .clear()
      .type(10)
      .should('have.value', 10)
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .clear()
      .type(5)
      .should('have.value', 5)
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .clear()
      .type('cypress{enter}')
      .get('[class=css-1rhbuit-multiValue]')
      .contains('cypress')
    cy.get('[data-cy=submitProfile]')
      .click()

    cy.wait(3000)

    // check arbitrator settings
    cy.visit(Cypress.env('host'))
    cy.get('[data-cy=headerProfileToggler]').click()
    cy.wait(1000)
    cy.get('[data-cy=profile]').contains('Profile').click()
    cy.wait(2000)
    cy.get('[data-cy=arbitratorSettingsCollapse]')
      .click()
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .should('have.value', 10)
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .should('have.value', 5)
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .get('[class=css-1rhbuit-multiValue]')
      .contains('cypress')

    // disable arbitrator
    cy.get('[data-cy=arbitratorSettingsFeeFlat]')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsFeePercentage]')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsTags]')
      .click()
      .get('[data-cy=arbitratorSettingsTags] input')
      .clear()
      .should('be.empty')
    cy.get('[data-cy=arbitratorSettingsEnabled]')
      .parent()
      .click('left')
    cy.get('[data-cy=submitProfile]')
      .click()

    // check profile
    cy.get('[data-cy=profileBio]')
      .should('have.value', "Ceci n'est pas une biographie.")
    cy.get('[data-cy=profileAddress]')
      .should('have.value', "Viale Regina Margherita, 71")
    cy.get('[data-cy=profileAddressCity]')
      .should('have.value', "Cagliari")
    cy.get('[data-cy=profileAddressZip]')
      .should('have.value', "09124")
    cy.get('[data-cy=profileAddressState]')
      .should('have.value', "CA")
    cy.get('[data-cy=profileAddressCountry]')
      .should('have.value', "Italy")
  })
})