mutation algorandFinalizeTransaction(
  $hash_round: String, 
  $round_sow: String, 
  $blob:String
) {
  algorandFinalizeTransaction(
    hash_round: $hash_round,
    round_sow: $round_sow
    blob: $blob
  ){
    hash_round
    round_sow
    blob
    sow
  }
}