mutation createSow{
  createSow {
    arbitrators
    arbitrator
    codeOfConduct
    currency
    seller
    buyer
    deadline
    description
    numberReviews
    price
    quantity
    tags
    termsOfService
    title
    sow
    createdAt
    updatedAt
    status
  }
}