mutation createSow{
  createSow {
    arbitrators
    codeOfConduct
    currency
    buyer
    deadline
    description
    numberReviews
    price
    quantity
    tags
    termsOfService
    title
    sow
  }
}