mutation draftSow(
  $sow: ID,
  $arbitrator: String,
  $codeOfConduct: Boolean,
  $currency: Currency,
  $buyer: String,
  $deadline: AWSDateTime,
  $description: String,
  $numberReviews: Int,
  $price: Float,
  $quantity: Int,
  $tags: [String],
  $termsOfService: Boolean,
  $title: String,
  $sowExpiration: Int,
  $licenseTermsOption: String,
  $licenseTermsNotes: String
) {
  draftSow(
    sow: $sow
    arbitrator: $arbitrator,
    codeOfConduct: $codeOfConduct,
    currency: $currency,
    buyer: $buyer,
    deadline: $deadline,
    description: $description,
    numberReviews: $numberReviews,
    price: $price,
    quantity: $quantity,
    tags: $tags,
    termsOfService: $termsOfService,
    title: $title,
    sowExpiration: $sowExpiration,
    licenseTermsOption: $licenseTermsOption,
    licenseTermsNotes: $licenseTermsNotes
  ) {
    sow
    arbitrator
    codeOfConduct
    currency
    buyer
    deadline
    description
    numberReviews
    price
    quantity
    tags
    termsOfService
    title
    createdAt
    updatedAt
    seller
    sowExpiration
    submittedDate
    licenseTermsOption
    licenseTermsNotes
  }
}