query getFullArbitrator(
  $user: String
  ){
    getFullArbitrator(
      user: $user
    ) {
      user
      enabled
      fee {
        flat
        perc
      }
      currency
      tags
      reputation
  }
}