query getFullArbitrator{
  getFullArbitrator{
      user
      enabled
      fee {
        feeType
        value
      }
      currency
      tags
      reputation
      given_name
      family_name
      public_key
      email
  }
}