query getSowListSeller{
  listSowsAsSeller {
    sows {
      sow
      arbitrators
      codeOfConduct
      currency
      deadline
      description
      numberReviews
      price
      quantity
      tags
      termsOfService
      title
      status
      buyer
      seller
      arbitrator
    }
    nextToken
  }
}