query listSowChatMessages(
  $sow: ID
  $after: AWSDateTime
){
  listSowChatMessages(
    sow: $sow
    after: $after
  ){
    messages {
      createdAt
      sow
      messageId
      textMessage {
        message
      }
      attachmentMessage {
        key
        size
        type
      }
      commandMessage {
        command
      }
      type
      modified
      from
    }
    nextToken
  }
}