query listSowChatMessages(
  $sow: ID
){
  listSowChatMessages(
    sow: $sow
  ){
    messages {
      createdAt
      sow
      messageId
      textMessage {
        message
      }
      attachmentMessage {
        key
        size
      }
      commandMessage {
        command
      }
      type
      modified
      from
    }
    nextToken
  }
}